apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sf-presto.fullname" . }}-worker
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
    app.kubernetes.io/version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "sf-presto.name" . }}-worker
      role: sfpresto-worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "sf-presto.name" . }}-worker
        role: sfpresto-worker
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
        role: sfpresto-worker
    spec:
      {{- if .Values.global.sfScheduler.enabled }}
      schedulerName: {{ .Values.global.sfScheduler.schedulerName }}
      {{- end }}
      containers:
        {{- if .Values.global.snappyflowKey }}
        - name: presto-worker-sfagent
          image: snappyflowml/sfagent:latest
          imagePullPolicy: Always
          command:
          - /app/sfagent
          - -config-file
          - /opt/sfagent/config.yaml
          - -enable-console-log
          env:
          - name: APP_NAME
            value: {{ .Values.global.snappyflowAppName }}
          - name: PROJECT_NAME
            value: {{ .Values.global.snappyflowProjectName }}
          volumeMounts:
          - name: sfagent
            mountPath: /opt/sfagent/config.yaml
            subPath: config.yaml  
        {{- end }}
        - name: sfpresto-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "./preStop.sh"]
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          command: ["/bin/bash", "-c"]
          args: ["./presto-init.sh;"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
          - name: hive-properties
            mountPath: /home/presto-server-0.282/etc/catalog
          - name: config
            mountPath: /home/presto-server-0.282/etc
        - name: sfpresto-worker-prometheus-exporter
          command: [/go/metrics]
          image: "{{ .Values.sfprestoWorkerPrometheusExporter.image.repository }}:{{ .Values.sfprestoWorkerPrometheusExporter.image.tag }}" 
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.sfprestoWorkerPrometheusExporter.resources | nindent 12 }}
      volumes:
      - name: hive-properties
        configMap:
          name: {{ include "sf-presto.fullname" . }}-catalog
      - name: config
        configMap:
          name: {{ include "sf-presto.fullname" . }}-worker
      - name: sfagent
        configMap:
          name: {{ include "sf-presto.fullname" . }}-sfagent
      terminationGracePeriodSeconds: {{ sub (mul .Values.env.Grace_Period_Seconds 2) 10 }}